name: 'Self-Hosted Action Polyfill'
description: 'Loads packages and libs that should be available in all hosted actions but aren`t in self-hosted'
icon: 'battery-charging'
color: 'gray-dark'
author: 'github.com/JPBM135'

input:
  ignore:
    description: 'List of modules and binaries to ignore'
    required: false
    default: []
    type: array
    items:
      type: string

  include:
    description: List of modules and binaries to include that aren\'t default
    required: false
    default: []
    type: array
    items:
      type: string

  skip-defaults:
    description: 'Ignore the default modules and binaries, only include the ones specified in the include input'
    required: false
    default: false
    type: boolean

  run-in-band:
    description: 'Run the installs in band, useful for debugging but will be slower'
    required: false
    default: false
    type: boolean

runs:
  using: 'node20'
  main: 'dist/index.mjs'
